---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: pcfdemo

run:
  path: pcfdemo/ci/tasks/unit.sh
  args: [
    --input-dir, pcfdemo
  ]
